/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalculadora extends javax.swing.JFrame {

    String entrada="";
double numero1  = 0, numero2= 0;
String operador = "";
    
   
    public jfrmCalculadora() {
        initComponents();
        jtxtCantidad.setText("0");
        this.setTitle("Calculadora básica");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn11 = new javax.swing.JButton();
        jbtnAC1 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();
        jbtnResul = new javax.swing.JButton();
        jbtnRaiz = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtnPor = new javax.swing.JButton();
        jbtnPunto = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnAC = new javax.swing.JButton();

        jbtn11.setText("%");
        jbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn11ActionPerformed(evt);
            }
        });

        jbtnAC1.setFont(new java.awt.Font("Segoe UI Light", 3, 5)); // NOI18N
        jbtnAC1.setText("AC");
        jbtnAC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAC1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setBackground(new java.awt.Color(204, 204, 255));
        jtxtCantidad.setText("0.0");

        jbtn7.setBackground(new java.awt.Color(153, 204, 255));
        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn8.setBackground(new java.awt.Color(153, 204, 255));
        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setBackground(new java.awt.Color(153, 204, 255));
        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn5.setBackground(new java.awt.Color(153, 204, 255));
        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.setBackground(new java.awt.Color(153, 204, 255));
        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn1.setBackground(new java.awt.Color(153, 204, 255));
        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setBackground(new java.awt.Color(153, 204, 255));
        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn4.setBackground(new java.awt.Color(153, 204, 255));
        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn0.setBackground(new java.awt.Color(153, 204, 255));
        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtn3.setBackground(new java.awt.Color(153, 204, 255));
        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnSuma.setBackground(new java.awt.Color(153, 204, 255));
        jbtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnSuma.setText("+");
        jbtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSumaActionPerformed(evt);
            }
        });

        jbtnResul.setBackground(new java.awt.Color(153, 204, 255));
        jbtnResul.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnResul.setText("=");
        jbtnResul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResulActionPerformed(evt);
            }
        });

        jbtnRaiz.setBackground(new java.awt.Color(153, 204, 255));
        jbtnRaiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnRaiz.setText("√");
        jbtnRaiz.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jbtnRaizAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jbtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRaizActionPerformed(evt);
            }
        });

        jbtnMulti.setBackground(new java.awt.Color(153, 204, 255));
        jbtnMulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnMulti.setText("*");
        jbtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiActionPerformed(evt);
            }
        });

        jbtnResta.setBackground(new java.awt.Color(153, 204, 255));
        jbtnResta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnResta.setText("-");
        jbtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRestaActionPerformed(evt);
            }
        });

        jbtnDivi.setBackground(new java.awt.Color(153, 204, 255));
        jbtnDivi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnDivi.setText("/");
        jbtnDivi.setToolTipText("");
        jbtnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDiviActionPerformed(evt);
            }
        });

        jbtnPor.setBackground(new java.awt.Color(153, 204, 255));
        jbtnPor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPor.setText("%");
        jbtnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPorActionPerformed(evt);
            }
        });

        jbtnPunto.setBackground(new java.awt.Color(153, 204, 255));
        jbtnPunto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPunto.setText(".");
        jbtnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPuntoActionPerformed(evt);
            }
        });

        jbtnC.setBackground(new java.awt.Color(153, 204, 255));
        jbtnC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jbtnCAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });

        jbtnAC.setBackground(new java.awt.Color(153, 204, 255));
        jbtnAC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAC.setText("AC");
        jbtnAC.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jbtnACAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jbtnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnACActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCantidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtn6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtnPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbtnResul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jbtnResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jbtnMulti)
                                                    .addComponent(jbtnDivi, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtn1, jbtn2, jbtn4, jbtn5, jbtn6, jbtn8, jbtn9, jbtnDivi, jbtnMulti});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn8)
                    .addComponent(jbtn9)
                    .addComponent(jbtnC)
                    .addComponent(jbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn4)
                        .addComponent(jbtn5)
                        .addComponent(jbtn6))
                    .addComponent(jbtnAC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1)
                    .addComponent(jbtn2)
                    .addComponent(jbtnDivi)
                    .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnMulti)
                        .addComponent(jbtnResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbtnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jbtnPunto)
                        .addComponent(jbtnResul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbtnRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtn1, jbtn2, jbtn4, jbtn5, jbtn6, jbtn8, jbtn9, jbtnDivi, jbtnMulti});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")){
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")){
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")){
            numero1 = numero1- numero2;
        } else if (operador.equals("*")){
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")){
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
        }
        
    operador = "+";
    }//GEN-LAST:event_jbtnSumaActionPerformed

    private void jbtnResulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResulActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")){
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")){
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")){
            numero1 = numero1- numero2;
        } else if (operador.equals("*")){
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")){
            numero1 = numero1 / numero2;
        } 
        entrada = String.valueOf(numero1);
        jtxtCantidad.setText(entrada);
        operador ="";
        }
                
        

    }//GEN-LAST:event_jbtnResulActionPerformed

    private void jbtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(entrada);
        
        if (valor >=0) {
            valor = Math.sqrt(valor);
            entrada = String.valueOf(valor);
        }else{
            entrada = "Error";
        }
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_jbtnRaizActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")){
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")){
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")){
            numero1 = numero1- numero2;
        } else if (operador.equals("*")){
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")){
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
        }
        
    operador = "*";
        
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")){
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")){
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")){
            numero1 = numero1- numero2;
        } else if (operador.equals("*")){
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")){
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
        }
        
    operador = "-";
        
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")){
        numero2 = Double.parseDouble(entrada);
        
        if (operador.equals("+")){
            numero1 = numero1 + numero2;
        } else if (operador.equals("-")){
            numero1 = numero1- numero2;
        } else if (operador.equals("*")){
            numero1 = numero1 * numero2;
        } else if (operador.equals("/")){
            numero1 = numero1 / numero2;
        } else {
            numero1 = numero2;
        }
        jtxtCantidad.setText(String.valueOf(numero1));
        entrada = "";
        }
        
    operador = "/";
        
    }//GEN-LAST:event_jbtnDiviActionPerformed

    private void jbtnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPorActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(entrada);
        valor = valor/ 100;
        entrada = String.valueOf(valor);
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnPorActionPerformed

    private void jbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn11ActionPerformed

    private void jbtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuntoActionPerformed
        // TODO add your handling code here:
        if (!entrada.contains(".")){
            if (entrada.equals("")){
                entrada = "0.";
            }else {
                entrada = entrada + ".";
            }
            jtxtCantidad.setText(entrada); 
        }
    }//GEN-LAST:event_jbtnPuntoActionPerformed

    private void jbtnAC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAC1ActionPerformed

    private void jbtnRaizAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jbtnRaizAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRaizAncestorAdded

    private void jbtnCAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jbtnCAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCAncestorAdded

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
        
        if (entrada.length()>1){
            entrada = entrada.substring(0, entrada.length()-1);        
        }else{
            entrada = "";
        }
        
        if (entrada.equals("")){
            jtxtCantidad.setText("0");
        }else {
            jtxtCantidad.setText(entrada);
        }
        
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnACAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jbtnACAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnACAncestorAdded

    private void jbtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnACActionPerformed
        // TODO add your handling code here:
        entrada = "";
    numero1 = 0;
    numero2 = 0;
    operador = "";
    jtxtCantidad.setText("0");
        
    }//GEN-LAST:event_jbtnACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn11;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAC;
    private javax.swing.JButton jbtnAC1;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnPor;
    private javax.swing.JButton jbtnPunto;
    private javax.swing.JButton jbtnRaiz;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JButton jbtnResul;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
